config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'home#index'

  # The post page that will send/retrieve data to/from the Weather API
  post 'home/weather_request', to: 'home#weather_request', as: 'weather_request'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Amalgamate error messages we may have received
  def collect_error_messages(errors)
    error_messages = []
    # Loop through errors and collect messages
    errors.each do |err_type, err_msg|
      error_messages << err_msg
    end
    error_messages
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    # Extract and delete the weather data hash from session
    weather_data = session.delete(:weather_data)&.deep_symbolize_keys

    # Determine if we have retrieved weather_data in the session.
    # If so, display it.
    if weather_data
      @is_cached = weather_data[:is_cached]
      @location_data = weather_data[:location]
      @weather_data = weather_data[:weather]
      @error_messages = weather_data[:error_messages]
    else
      # Default to nil if no session data is found
      @location_data = @weather_data = @is_cached = @error_messages = nil
    end
  end

  def weather_request 
    @zip_code = params[:zip_code]
    cache_key = "weather_#{@zip_code}"
    @is_cached = Utilities::AppUtils.is_cached?(cache_key)
    svc_request = FetchLocationAndWeatherService.call(@zip_code)
    
    if svc_request.result[:weather].present? 
      @location_data = svc_request.result[:location]
      @weather_data = svc_request.result[:weather]
      @error_messages = nil
    else
      # When weather data is missing, check for location errors
      location_err = find_location_error
      @error_messages = location_err.present? ? [location_err] : collect_svc_errors(svc_request)
    end

    respond_to do |format|
     
      flash[:error] = @error_messages if @error_messages.present?

      format.html do
        session[:weather_data] = {
          is_cached: @is_cached,
          location: @location_data, 
          weather: @weather_data,
          error_messages: @error_messages
        }
        redirect_to root_path
      end

      format.turbo_stream {
        render turbo_stream: [
          turbo_stream.update('weather_results',
            partial: 'home/weather_results',
            locals: { location_data: @location_data, weather_data: @weather_data , is_cached: @is_cached } 
          ),
          turbo_stream.update('flash', 
            partial: 'layouts/flash',
            locals: { messages: flash }
          )
        ]
      }
    end
  end

  private

  def find_location_error
    location_key = "location_#{@zip_code}"
    return nil unless Utilities::AppUtils.is_cached?(location_key)
    
    location_cache = Rails.cache.read(location_key)
    location_cache[:err_message].present? ? location_cache[:err_message] : nil
  end

  def collect_svc_errors(svc_request)
    svc_request.errors&.any? ? collect_error_messages(svc_request.errors) : []
  end

  def weather_request_params
    # Permit only the expected parameters
    params.require(:zip_code).permit(:zip_code)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def cache_duration_and_units
    # Read cache settings from the config file
    cache_config = YAML.load_file(Rails.root.join('config', 'cache_config.yml'))[Rails.env].symbolize_keys
    cache_duration = cache_config[:cache_location_duration]
    cache_units = cache_config[:cache_location_units]
    
    "#{cache_duration} #{cache_units}"
  end
end

app/views/home/_weather_results.html.erb
<div id="weather_results">
  <% if location_data.present? && weather_data.present? %>
    <h2 style="margin-bottom: -2px">
      <%= "Weather Results for #{location_data[:city]}, 
            #{location_data[:state]}  
            #{location_data[:zip_code]}" %>
    </h2>
    <% if is_cached %>
      <span style="color: #A020F0; font-style: italic;">
        This data is cached ... check back in <%= cache_duration_and_units %> or so for updates
      </span>
    <% end %>
  <% end %>

  <% if weather_data.present? %>
    <h2>Current Weather</h2>
    <p><strong>Date:</strong> <%= weather_data[:current][:dt] %></p>
    <p><strong>Temperature:</strong> <%= weather_data[:current][:temp] %> degrees Farenheit</p>
    <p><strong>Conditions:</strong> <%= weather_data[:current][:conditions] %></p>
    <p><%= image_tag weather_data[:current][:icon], alt: "image depicting weather forecast" %></p>
    <hr />
    <h2>Extended Forecast</h2>
    <% weather_data[:forecast].each do |day| %>
      <p><strong>Date:</strong> <%= day[:dt] %></p>
      <p><strong>High:</strong> <%= day[:max_temp] %> degrees Farenheit</p>
      <p><strong>Low:</strong> <%= day[:min_temp] %> degrees Farenheit</p>
      <p><strong>Conditions:</strong> <%= day[:conditions] %></p>
      <p><%= image_tag day[:icon], alt: "image depicting weather forecast" %></p>
      <hr />
    <% end %>
  <% end %>
</div>

app/views/home/index.html.erb
<h1>Welcome to the Weather App!</h1>

<!-- Zip Code Entry -->
<div id="weather_request">
  <p> Enter a 5-digit U.S. Zip Code to view the forecast for that location:</p>
  <%= form_with url: weather_request_path, method: :post, remote: true do |f| %>
    <%= f.text_field :zip_code, :maxlength => 5, style: "width: 150px", placeholder: "Zip Code" %>
    <%= f.submit "Get Forecast" %>
  <% end %>
  <div><i>Postal Code lookups are only available for the U.S.</i></div>
</div>

<!-- Weather Forecast Results -->
<%= turbo_frame_tag "weather_info" do %>
  <%= render partial: "home/weather_results",
    locals: {
      location_data: @location_data,
      weather_data: @weather_data,
      is_cached: @is_cached
    } 
  %>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
<div class="flash_message" data-controller="flash">
  <% if message.is_a?(Array) %>
    <% message.each do |msg| %>
      <div><%= msg %></div>
    <% end %>
  <% else %>
    <%= message %>
  <% end %>
</div>
<% end %>
<% flash.clear %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherForecastApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="flash" class="flash">
      <%= render "layouts/flash" %>
    </div>
    <%= yield %>
  </body>
</html>